var car = "Subaru";
var bike = "BMW S1000R";
var game = "Valorant";
var day = "Tuesday";
var month = 4;
console.log("Is the car Subaru? I predict true");
console.log(car == 'Subaru');
console.log("\nIs the car Koenigsegg? I predict false");
console.log(car == 'Koenigesegg');
console.log("\nIs the bike BMW S1000R? I predict true");
console.log(bike == 'BMW S1000R');
console.log("\nIs the bike Kawasaki Ninja H2? I predict false");
console.log(bike == 'Kawasaki Ninja H2');
console.log("\nIs the game Valorant? I predict true");
console.log(game == 'Valorant');
console.log("\nIs the game COD? I predict false");
console.log(game == 'COD');
console.log("\nIs the day Tuesday? I predict true");
console.log(day == 'Tuesday');
console.log("\nIs the day Monday? I predict false");
console.log(day == 'Monday');
console.log("\nIs the month 4? I predict true");
console.log(month == 4);
console.log("\nIs the month 3? I predict false");
console.log(month == 3);
