var car = "Mclaren P1";
console.log("Is the car Mclaren P1? I predict true");
console.log(car == 'Mclaren P1');
console.log("\nIs the car Pagani Huayra? I predict false");
console.log(car == 'Pagani Huayra');
var country = "UAE";
var lowerCountry = country.toLowerCase();
console.log("\nIs lowercase Country uae? I Predict true");
console.log(lowerCountry == 'uae');
var num1 = 30;
var num2 = 20;
console.log("\nIs num1 greater than num2? I predict true.");
console.log(num1 > num2);
console.log("\nIs num1 equal to num2? I predict false.");
console.log(num1 == num2);
var temperature = 10;
var winter = true;
console.log("\nIs the temperature 10C and winter? I predict true");
console.log(temperature == 10 && winter == true);
console.log("\nIs the temperature 8C or winter? I predict true");
console.log(temperature == 10 || winter == true);
var fruits = ['apple', 'banana', 'mango'];
console.log("\nIs apple in the fruits array? I predict true.");
console.log(fruits.includes('apple'));
console.log("\nIs guava in the fruits array? I predict false.");
console.log(fruits.includes('guava'));
